# name of the software
name: Generic Project
# licence of the software
license: Apache 2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

# list of additional links on the right of the top menu
headerLinks:
#  - title: GitHub
#    url: https://github.com/mistic100/jekyll-bootstrap-doc

# list if additional links on the footer
footerLinks:
  - title: <i class="fa fa-github"></i>GitHub
    url: https://github.com/mistic100/jekyll-bootstrap-doc
  - title: <i class="fa fa-exclamation-circle"></i>Issues
    url: https://github.com/mistic100/jekyll-bootstrap-doc/issues?state=open

# header
header:
  #color1: "#D43F3A"
  #color2: "#D4813A"
  color1: "#e64c29"
  color2: "#e64c29"

rockstore:
  url:

# google analytics
analytics:
  account:
  domain:

# github buttons
github:
  user: BricksandMortar
  repo: IdealPostcodes

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: arranf


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
